In [3]:
import pandas as pd

### Соединяем паралленьные таблицы

In [4]:
wallget_0 = pd.read_csv('csv_files/posts.csv')
wallget_1 = pd.read_csv('csv_files/posts_1.csv')

df_wall = pd.concat([wallget_0, wallget_1], ignore_index=True)
df_wall = df_wall.drop(columns=['geo', 'zoom_text', 'author_ad', 'signer_id'], errors='ignore')
df_wall.shape

(2626, 27)

In [5]:
videoget_0 = pd.read_csv('csv_files/videos.csv')
videoget_1 = pd.read_csv('csv_files/videos_1.csv')

df_video = pd.concat([videoget_0, videoget_1], ignore_index=True)
df_video.shape

(12869, 15)

In [6]:
groupsget_0 = pd.read_csv('csv_files/groups.csv')
groupsget_1 = pd.read_csv('csv_files/groups_1.csv')

df_groups = pd.concat([groupsget_0, groupsget_1], ignore_index=True)
df_groups.shape

(26, 20)

In [7]:
df_groups.columns

Index(['id', 'description', 'members_count', 'activity', 'status', 'contacts',
       'site', 'age_limits', 'name', 'screen_name', 'is_closed', 'type',
       'is_admin', 'is_member', 'is_advertiser', 'verified', 'photo_50',
       'photo_100', 'photo_200', 'city'],
      dtype='object')

In [8]:
df_groups = df_groups.drop(columns = ['age_limits', 'is_closed', 'type'    , 'is_admin' , 'is_member', 'is_advertiser', 
                                      'photo_50'  , 'photo_100', 'contacts', 'photo_200', 'city'     ,], errors = 'ignore')

In [9]:
df_groups.head()

,id,description,members_count,activity,status,site,name,screen_name,verified
0,211229778,"Шоу, в котором четыре девушки дают советы по л...",706762,"Шоу, передача",NaN,https://www.youtube.com/channel/UCXDerjAwOSH30...,Женский Форум,zhenforum,1
1,209976560,ОФИЦИАЛЬНАЯ СТРАНИЦА LABELCOM,1618634,Юмор,NaN,http://mediumquality.ru/,LABELCOM,labelcom,1
2,203677279,ИМПРОКОМ — это новое название нашего канала. \...,997914,"Шоу, передача",Новое видео уже на канале! Смотри😉,NaN,Импроком,improcom,1
3,165221845,Это группа нового проекта от Гарика Харламова ...,556393,Юмор,NaN,NaN,ОХ,ox.show,1
4,110135406,Азамат Мусагалиев\n#камызяки / #однаждывроссии...,1712188,Комик,Сериал А.М. уже в сообществе!,NaN,Азамат Мусагалиев,azamatmusagaliev,1

In [10]:
getcomments_0 = pd.read_csv('csv_files/comments.csv')
getcomments_1 = pd.read_csv('csv_files/comments_1.csv')

df_comments = pd.concat([getcomments_0, getcomments_1], ignore_index=True)
df_comments.shape

(12758, 3)

### Делаем два итоговых датасета

#### Видео

In [ ]:
df_video.columns

Index(['id', 'owner_id', 'group_name', 'title', 'description', 'duration',
       'date', 'views', 'comments', 'player', 'can_like', 'can_repost',
       'can_dislike', 'is_pinned', 'album_video_percent'],
      dtype='object')

In [ ]:
df_video = df_video.drop(columns = ['player'], errors = 'ignore')

In [ ]:
df_video["owner_id"] = df_video["owner_id"].abs()
df_comments["owner_id"] = df_comments["owner_id"].abs()

df_video_comments = df_video.merge(df_comments, on=["owner_id", "id"], how="left")

In [ ]:
df_video_comments.head()

,id,owner_id,group_name,title,description,duration,date,views,comments,can_like,can_repost,can_dislike,is_pinned,album_video_percent,top_comment_text
0,456239756,211229778,Женский форум,Женский Форум #79,"Сделай подарок любимым, а МТС Live подарит теб...",4000,1740042000,5395319,975.0,1,1,1,False,96.2,❤️❤️❤️любимки . Смотрим
1,456239748,211229778,Женский форум,Женский Форум #78 | Алексей Смирнов,Получайте повышенный кешбэк с МТС Premium в се...,3385,1738832400,5364194,776.0,1,1,1,False,96.2,золотистая барабулька
2,456239738,211229778,Женский форум,Женский Форум #77,"Технологии флагманов, премиальный дизайн, неве...",3993,1738054800,4543591,780.0,1,1,1,False,96.2,Первая
3,456239719,211229778,Женский форум,Женский Форум #76 | Ольга Бузова | Новогодний,"С VoiceTech от МТС не нужно быть айтишником, ч...",4574,1735549200,5911643,1940.0,1,1,1,False,96.2,новогодняя барабулька
4,456239713,211229778,Женский форум,Женский Форум #75 | Александр Рогов | Новогодний,Еще больше полезных новостей в сообществе Ozon...,4055,1735376400,4014250,891.0,1,1,1,False,96.2,новогодняя барабулька

In [ ]:
df_full_video = df_video_comments.merge(df_groups, left_on="owner_id", right_on="id", how="left")

In [ ]:
df_full_video.to_csv("csv_files/df_video.csv", index=False, encoding="utf-8")

In [ ]:
df_full_video.shape

(12870, 24)

#### Стена

In [11]:
df_wall.columns

Index(['inner_type', 'donut', 'is_pinned', 'comments', 'marked_as_ads', 'hash',
       'type', 'push_subscription', 'attachments', 'date', 'from_id', 'id',
       'is_favorite', 'likes', 'reaction_set_id', 'reactions', 'owner_id',
       'post_source', 'post_type', 'reposts', 'text', 'views', 'edited',
       'carousel_offset', 'copy_history', 'donut_miniapp_url', 'check_sign'],
      dtype='object')

In [12]:
df_wall = df_wall.drop(columns = ['inner_type', 'push_subscription', 'hash'        , 'reaction_set_id', 'post_type',
                                  'edited'    , 'carousel_offset'  , 'copy_history', 'is_favorite'    , 'type'     ,
                                  'donut'     ,], errors = 'ignore')

In [13]:
df_wall["owner_id"] = df_wall["owner_id"].abs()
df_wall_groups = df_wall.merge(df_groups, left_on="owner_id", right_on="id", how="left")

In [14]:
df_wall_groups.shape

(2626, 25)

In [15]:
df_wall_groups.to_csv("csv_files/df_wall.csv", index=False, encoding="utf-8")